### ISSUE TITLE
JOSS paper checklist

### ISSUE THREAD

**Issue by hscannell** [ocetrac/ocetrac#26]
Reviewer checklist for JOSS submission:
https://joss.readthedocs.io/en/latest/review_criteria.html

### General checks 

- [x] **Repository**: Is the source code for this software available at the repository url?

- [x] **License**: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

- [x] **Contribution and authorship**: Has the submitting author made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

#### Functionality

- [x] **Installation**: Does installation proceed as outlined in the documentation?

- [x] **Functionality**: Have the functional claims of the software been confirmed?

- [x] **Performance**: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

#### Documentation

- [x] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

- [x] **Installation instructions**: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

- [x] **Example usage**: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

- [x] **Functionality documentation**: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

- [x] **Automated tests**: Are there automated tests or manual steps described so that the functionality of the software can be verified?

- [x] **Community guidelines**: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

#### Software paper

- [x] **Summary**: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?

- [x] **A statement of need**: Does the paper have a section titled ‘Statement of Need’ that clearly states what problems the software is designed to solve and who the target audience is?

- [x] **State of the field**: Do the authors describe how this software compares to other commonly-used packages?

- [x] **Quality of writing**: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?

- [x] **References**: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

**Comment by hscannell** [comment]
The [paper](https://github.com/ocetrac/ocetrac/blob/main/paper/paper.md) is ready to be reviewed 😁 
@rabernat and @jbusecke 

[Link](https://github.com/ocetrac/ocetrac/suites/4124936985/artifacts/105527784) to download the PDF.

**Comment by hscannell** [comment]
- [ ]  We need a grant number for the Gordon Betty Moore Foundation

**Comment by rabernat** [comment]
Great work! :+1: I will definitely be able to review this and give my comments within the next few days.

**Comment by rabernat** [comment]
See suggestions in #28

**Comment by CassiaCai** [comment]
Closing because we created a new issue for 2026 JOSS submission #78
